disabled_rules: # rule identifiers to exclude from running

opt_in_rules: # some rules are only opt-in
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  # Find all the available rules by running:
  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
#excluded: # paths to ignore during linting. Takes precedence over `included`.

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
trailing_semicolon: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
comma: error
statement_position:
  statement_mode: uncuddled_else

nesting:
  type_level:
    warning: 3
    error: 4

line_length: 200

reporter: xcode

large_tuple:
  warning: 4
  error: 4

type_name:
  min_length: 2
  max_length: 40
  excluded: T

identifier_name:
  min_length: 2
  max_length: 40

cyclomatic_complexity:
  ignores_case_statements: true
